name: Muhammad Adnan Khalid Deploy website

on:
  push:
    branch: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2
    -  name: Install Nodejs
       uses: actions/setup-node@v2
       with:
         node-version: 12
    -  name: Install Surge
       run: npm install -g surge
    -  name: Run Surge
       run: surge ./ htmltest123.surge.sh --token ${{secrets.SURGE_TOKEN}}
